### ISSUE TITLE
how does filewalker determine when an async task is done? WAS: How does maxPending actually work

### ISSUE THREAD

**Issue by matylla** [oleics/node-filewalker#12]
Say I have 1.000.000 files and for each file I need to do some heavy processing. So I limit the `maxPending` to say 10 at a time. 

```
filewalker("directory", { maxPending: 10 })
    .on("file", function (path) {
        // some heavy and very long processing here
    })
    .on("error", function (err) {
        console.error(err);
    }).walk();
```

The question is - how does filewalker determine when the async task is done? I was expecting a callback function I can call once I'm done processing an entry so that filewalker can emit another `file` event.

**Comment by oleics** [comment]
> how does filewalker determine when the async task is done?

It don't, no need for it. It's the 'stream'-event, which in case of reaching `maxPending` waits for the 'close'-event of the readable file-stream passed to the handler of the 'stream'-event.

Example:

``` js
filewalker('/', { maxPending: 10 })

  .on('stream', function(readableStream, relativePath, statObject, fullPath) {
    // run some heavy processing on readableStream
    // maybe calculate the hash
    var hash = createHash('md5');
    readableStream.on('data', function(data) {
      hash.update(data);
    });
    readableStream.on('end', function(data) {
      console.log(hash.digest('hex'), ('                '+s.size).slice(-16), p);
    });
  })

  .on('error', function(err) {
    // some error did happen, log
    console.log(err.stack||err);
  })

  .on('done', function() {
    // done processing all files.
    console.log('OK');
  })
.walk();
```

A sidenote: Keep in mind that (for readable file-streams) the 'end'-event always happens before the 'close'-event.
