### ISSUE TITLE
Symbolic links aren't processed properly on a Mac

### ISSUE THREAD

**Issue by ykagan** [oleics/node-filewalker#6]
The following code fails because symbolic links are neither directories nor files:

     if(s.isDirectory()) {
        self.enqueue(self._emitDir, [self._path(p), s, p]);
      } else {
        if(!self.matchRegExp || self.matchRegExp.test(p)) {
          self.enqueue(self._emitFile, [self._path(p), s, p]);
        }
      }

we should at least add s.isFile(), and optionally follow the symlink when traversing the tree

**Comment by oleics** [comment]
hi

this was intended behavior the time it was written

pull-request anyone? ^^

cheers

**Comment by oleics** [comment]
But please consider that you can handle that error:

```js
filewalker('.')
  .on('error', function(err) {
    console.error(err);
  })
.walk();
```

So, if someone really needs to travers symbolic links too and implements something that avoids circular walks: pull-requests :)
